In [2]:
import torch

A = torch.arange(20).reshape(5, 4)
B = torch.arange(20).reshape(5, 4)
print(A.T.T == A)
print(A.T + B.T == (A + B).T)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])


In [3]:
C = torch.arange(24).reshape(2, 3, 4)
print(len(C))
print(A)
print(A.sum(axis=1))
#print(A / A.sum(axis=1))

2
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([ 6, 22, 38, 54, 70])


In [4]:
print(C.sum(axis=0))
print(C.sum(axis=1))
print(C.sum(axis=2))

tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])
tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])
tensor([[ 6, 22, 38],
        [54, 70, 86]])
